/**
 * chatExport.js — Download and Share utilities for Dr.AI conversations
 * 
 * Features:
 *  - Download as TXT
 *  - Download as PDF (using browser print)
 *  - Share via link (copies a shareable URL to clipboard)
 */

// ── Download as TXT ────────────────────────────────────────────────────────────
export function downloadAsTXT(chat, conversationTitle = "Healthcare Consultation") {
  const lines = [
    `Dr.AI — ${conversationTitle}`,
    `Exported on: ${new Date().toLocaleString()}`,
    `${"─".repeat(50)}`,
    "",
    ...chat.map(msg => {
      const speaker =
        msg.role === "patient" ? "You" :
        msg.role === "doctor"  ? "Dr.AI" : "System";
      return `[${speaker}]\n${msg.text}\n`;
    })
  ];

  const content = lines.join("\n");
  const blob    = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url     = URL.createObjectURL(blob);

  triggerDownload(url, `DrAI_${sanitizeFilename(conversationTitle)}.txt`);
  URL.revokeObjectURL(url);
}


// ── Download as PDF ────────────────────────────────────────────────────────────
export function downloadAsPDF(chat, conversationTitle = "Healthcare Consultation") {
  // Build a clean HTML page and print it as PDF
  const rows = chat.map(msg => {
    const speaker =
      msg.role === "patient" ? "You" :
      msg.role === "doctor"  ? "Dr.AI" : "System";

    const bgColor =
      msg.role === "patient" ? "#e8f4fd" :
      msg.role === "doctor"  ? "#f0f9f0" : "#fff3f3";

    const labelColor =
      msg.role === "patient" ? "#1a6fa6" :
      msg.role === "doctor"  ? "#1a6a2a" : "#a61a1a";

    return `
      <div style="
        margin: 10px 0;
        padding: 12px 16px;
        background: ${bgColor};
        border-radius: 10px;
        font-size: 13px;
        line-height: 1.6;
        page-break-inside: avoid;
      ">
        <div style="
          font-weight: 700;
          font-size: 11px;
          color: ${labelColor};
          text-transform: uppercase;
          letter-spacing: 0.05em;
          margin-bottom: 6px;
        ">${speaker}</div>
        <div style="color: #1a1a1a;">${escapeHtml(msg.text)}</div>
        ${msg.meta ? `<div style="font-size: 11px; color: #888; margin-top: 4px;">${escapeHtml(msg.meta)}</div>` : ""}
      </div>
    `;
  }).join("");

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>Dr.AI — ${escapeHtml(conversationTitle)}</title>
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
          font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
          padding: 40px;
          color: #1a1a1a;
          background: #fff;
        }
        .header {
          border-bottom: 2px solid #667eea;
          padding-bottom: 16px;
          margin-bottom: 24px;
        }
        .brand {
          display: flex;
          align-items: center;
          gap: 10px;
          margin-bottom: 8px;
        }
        .brand-logo {
          width: 32px; height: 32px;
          background: linear-gradient(135deg, #667eea, #764ba2);
          border-radius: 8px;
          display: flex; align-items: center; justify-content: center;
          color: white; font-weight: bold; font-size: 14px;
        }
        .brand-name { font-size: 20px; font-weight: 700; color: #1a1a1a; }
        .meta { font-size: 12px; color: #888; }
        .footer {
          margin-top: 32px;
          padding-top: 16px;
          border-top: 1px solid #eee;
          font-size: 11px;
          color: #aaa;
          text-align: center;
        }
        @media print {
          body { padding: 20px; }
        }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="brand">
          <div class="brand-logo">AI</div>
          <div class="brand-name">Dr.AI</div>
        </div>
        <div style="font-size: 15px; font-weight: 600; color: #333; margin-bottom: 4px;">
          ${escapeHtml(conversationTitle)}
        </div>
        <div class="meta">Exported on ${new Date().toLocaleString()}</div>
      </div>

      <div class="messages">${rows}</div>

      <div class="footer">
        Generated by Dr.AI Healthcare Chatbot · For educational purposes only · Not a substitute for real medical advice
      </div>
    </body>
    </html>
  `;

  // Open in new window and trigger print dialog (Save as PDF)
  const printWindow = window.open("", "_blank", "width=800,height=900");
  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.focus();

  // Small delay to ensure content loads before printing
  setTimeout(() => {
    printWindow.print();
  }, 500);
}


// ── Share via Link ─────────────────────────────────────────────────────────────
export async function shareConversationLink(conversationId, conversationTitle) {
  if (!conversationId) {
    alert("Please send a message first to create a conversation before sharing.");
    return false;
  }

  // Build a shareable URL — points to the current app with conversation ID
  const baseUrl = window.location.origin;
  const shareUrl = `${baseUrl}?conversation=${conversationId}`;

  try {
    // Try native Web Share API first (works on mobile)
    if (navigator.share) {
      await navigator.share({
        title: `Dr.AI — ${conversationTitle}`,
        text:  "Check out this healthcare consultation on Dr.AI",
        url:   shareUrl,
      });
      return true;
    }

    // Fallback: copy to clipboard
    await navigator.clipboard.writeText(shareUrl);
    return "copied";

  } catch (err) {
    // Final fallback: manual copy
    const textArea = document.createElement("textarea");
    textArea.value = shareUrl;
    document.body.appendChild(textArea);
    textArea.select();
    document.execCommand("copy");
    document.body.removeChild(textArea);
    return "copied";
  }
}


// ── Helpers ────────────────────────────────────────────────────────────────────
function triggerDownload(url, filename) {
  const a    = document.createElement("a");
  a.href     = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
}

function sanitizeFilename(name) {
  return name.replace(/[^a-z0-9]/gi, "_").substring(0, 40);
}

function escapeHtml(text) {
  if (!text) return "";
  return text
    .replace(/&/g,  "&amp;")
    .replace(/</g,  "&lt;")
    .replace(/>/g,  "&gt;")
    .replace(/"/g,  "&quot;")
    .replace(/'/g,  "&#039;");
}