import React, { useState, useRef } from "react";
import "./MedicalReportAnalyzer.css";
import BACKEND_URL from "./config";

const STATUS_CONFIG = {
  normal:     { color: "green",  icon: "✅", label: "Normal"     },
  high:       { color: "red",    icon: "🔴", label: "High"       },
  low:        { color: "red",    icon: "🔴", label: "Low"        },
  borderline: { color: "yellow", icon: "⚠️", label: "Borderline" },
  info:       { color: "grey",   icon: "ℹ️", label: "Info"       },
};

const val = (v) => (v && v !== "null" && v !== "undefined") ? v : "Unknown";

export default function MedicalReportAnalyzer({ currentUser, activeMember, onClose }) {
  const [file, setFile]         = useState(null);
  const [preview, setPreview]   = useState(null);
  const [loading, setLoading]   = useState(false);
  const [result, setResult]     = useState(null);
  const [error, setError]       = useState("");
  const [dragOver, setDragOver] = useState(false);
  const [downloading, setDownloading] = useState(false);
  const fileRef    = useRef();
  const resultRef  = useRef();

  const memberName = activeMember?.name || currentUser?.displayName || "You";

  const handleFile = (f) => {
    if (!f) return;
    const allowed = ["image/jpeg","image/png","image/jpg","application/pdf"];
    if (!allowed.includes(f.type)) { setError("Please upload JPG, PNG or PDF."); return; }
    if (f.size > 10 * 1024 * 1024) { setError("File too large. Max 10MB."); return; }
    setFile(f); setError(""); setResult(null);
    setPreview(f.type !== "application/pdf" ? URL.createObjectURL(f) : null);
  };

  const handleDrop = (e) => {
    e.preventDefault(); setDragOver(false);
    handleFile(e.dataTransfer.files[0]);
  };

  const toBase64 = (f) => new Promise((res, rej) => {
    const r = new FileReader();
    r.onload  = () => res(r.result.split(",")[1]);
    r.onerror = rej;
    r.readAsDataURL(f);
  });

  const analyzeReport = async () => {
    if (!file) { setError("Please upload a report first."); return; }
    setLoading(true); setError(""); setResult(null);
    try {
      const base64 = await toBase64(file);
      const fd     = new FormData();
      fd.append("file_base64", base64);
      fd.append("file_type",   file.type);
      fd.append("file_name",   file.name);
      fd.append("member_name", memberName);
      const res  = await fetch(`${BACKEND_URL}/analyze-report`, { method:"POST", body:fd });
      if (!res.ok) throw new Error(`Server error: ${res.status}`);
      const data = await res.json();
      if (data.error) throw new Error(data.error);
      setResult(data);
    } catch(e) {
      setError("Failed to analyze. Make sure backend is running.");
      console.error(e);
    } finally { setLoading(false); }
  };

  const reset = () => { setFile(null); setPreview(null); setResult(null); setError(""); };

  // ── PDF Download ─────────────────────────────────────────────────────────
  const downloadPDF = async () => {
    if (!result) return;
    setDownloading(true);
    try {
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF({ orientation:"portrait", unit:"mm", format:"a4" });
      const pw=210, ml=15, mr=195;
      let y = 15;
      const addLine  = (h=4)    => { y += h; };
      const checkPage= (need=20)=> { if(y+need>275){ doc.addPage(); y=15; } };
      const clean    = (s)      => (s||"").replace(/[^\x00-\x7F]/g, "");  // strip non-ASCII

      // ── Green header bar ─────────────────────────────────────────────
      doc.setFillColor(16,185,129);
      doc.rect(0,0,pw,24,"F");
      doc.setTextColor(255,255,255);
      doc.setFontSize(17); doc.setFont("helvetica","bold");
      doc.text("Medical Report Analysis", ml, 11);
      doc.setFontSize(9); doc.setFont("helvetica","normal");
      doc.text(`Generated by Dr.AI  |  ${new Date().toLocaleDateString("en-IN",{day:"numeric",month:"long",year:"numeric"})}`, ml, 19);
      y = 32;

      // ── Report type + status badge ───────────────────────────────────
      doc.setTextColor(20,20,20);
      doc.setFontSize(15); doc.setFont("helvetica","bold");
      doc.text(clean(result.report_type)||"Lab Report", ml, y); addLine(8);

      const sc = result.overall_status==="abnormal" ? [220,38,38]
               : result.overall_status==="borderline" ? [217,119,6] : [5,150,105];
      doc.setFillColor(...sc);
      doc.roundedRect(ml, y, 52, 8, 2, 2, "F");
      doc.setTextColor(255,255,255); doc.setFontSize(9); doc.setFont("helvetica","bold");
      const blabel = result.overall_status==="abnormal" ? "! Needs Attention"
                   : result.overall_status==="borderline" ? "Borderline" : "Looks Good";
      doc.text(blabel, ml+3, y+5.5);
      addLine(13);

      // ── Patient details box ──────────────────────────────────────────
      doc.setFillColor(245,247,250);
      doc.setDrawColor(210,214,220);
      doc.roundedRect(ml, y, mr-ml, 40, 3, 3, "FD");

      doc.setFontSize(9); doc.setFont("helvetica","bold"); doc.setTextColor(5,150,105);
      doc.text("PATIENT DETAILS", ml+4, y+7);

      const p = result.patient||{};
      const c1=ml+4, c2=ml+68, c3=ml+132;
      doc.setFontSize(8.5); doc.setTextColor(50,50,50);

      const prow=(label,value,x,yy)=>{
        doc.setFont("helvetica","bold");   doc.text(label+":", x, yy);
        doc.setFont("helvetica","normal"); doc.text(clean(value)||"Unknown", x+doc.getTextWidth(label+": ")+1, yy);
      };
      prow("Name",    val(p.name)!=="Unknown"?val(p.name):memberName, c1, y+16);
      prow("Age",     val(p.age),     c2, y+16);
      prow("Gender",  val(p.gender),  c3, y+16);
      prow("ID",      val(p.patient_id), c1, y+25);
      prow("Ref. By", val(p.referred_by),c2, y+25);
      prow("Lab",     val(p.lab_name),   c1, y+34);
      prow("Date",    val(result.report_date), c2, y+34);
      y += 46;

      // ── Summary ──────────────────────────────────────────────────────
      checkPage(28);
      doc.setFontSize(9.5); doc.setFont("helvetica","bold"); doc.setTextColor(20,20,20);
      doc.text("SUMMARY", ml, y); addLine(1);
      doc.setDrawColor(16,185,129); doc.setLineWidth(0.4);
      doc.line(ml, y, ml+30, y); addLine(5);
      doc.setFontSize(9); doc.setFont("helvetica","normal"); doc.setTextColor(70,70,70);
      const sumLines = doc.splitTextToSize(clean(result.summary)||"", mr-ml);
      doc.text(sumLines, ml, y);
      y += sumLines.length*5+8;

      // ── Test results ─────────────────────────────────────────────────
      checkPage(20);
      doc.setFontSize(9.5); doc.setFont("helvetica","bold"); doc.setTextColor(20,20,20);
      doc.text("TEST RESULTS", ml, y); addLine(1);
      doc.setDrawColor(16,185,129); doc.line(ml, y, ml+36, y); addLine(5);

      // Table header
      doc.setFillColor(235,238,242);
      doc.rect(ml, y, mr-ml, 7, "F");
      doc.setFontSize(7.5); doc.setFont("helvetica","bold"); doc.setTextColor(90,90,90);
      doc.text("TEST NAME",    ml+3,  y+5);
      doc.text("VALUE",        ml+75, y+5);
      doc.text("NORMAL RANGE", ml+103,y+5);
      doc.text("STATUS",       ml+148,y+5);
      addLine(9);

      (result.tests||[]).forEach(t => {
        checkPage(14);
        const isLow  = t.status==="low";
        const isHigh = t.status==="high";
        const isBord = t.status==="borderline";
        const isNorm = t.status==="normal";

        const rowBg  = isHigh||isLow ? [255,241,241]
                     : isBord        ? [255,252,235]
                     : isNorm        ? [241,255,250] : [250,250,250];
        const barClr = isHigh||isLow ? [220,38,38]
                     : isBord        ? [217,119,6]
                     : isNorm        ? [16,185,129]  : [170,170,170];
        const stLabel= isHigh ? "HIGH" : isLow ? "LOW" : isBord ? "BORDERLINE" : isNorm ? "NORMAL" : "INFO";

        doc.setFillColor(...rowBg);
        doc.setDrawColor(215,215,215);
        doc.rect(ml, y-4, mr-ml, 13, "FD");
        doc.setFillColor(...barClr);
        doc.rect(ml, y-4, 2.5, 13, "F");

        doc.setFontSize(8); doc.setFont("helvetica","bold"); doc.setTextColor(25,25,25);
        doc.text(clean(t.name)||"", ml+5, y+1);
        doc.setFont("helvetica","normal"); doc.setFontSize(6.5); doc.setTextColor(110,110,110);
        const expLine = doc.splitTextToSize(clean(t.explanation)||"", 62);
        doc.text(expLine[0]||"", ml+5, y+7);

        doc.setFontSize(8.5); doc.setFont("helvetica","bold"); doc.setTextColor(25,25,25);
        doc.text(`${clean(t.value)||""} ${clean(t.unit)||""}`, ml+75, y+3);

        doc.setFontSize(7.5); doc.setFont("helvetica","normal"); doc.setTextColor(90,90,90);
        doc.text(clean(t.normal_range)||"-", ml+103, y+3);

        // Status badge (colored rectangle + white text)
        doc.setFillColor(...barClr);
        doc.roundedRect(ml+145, y-1, 34, 7, 1.5, 1.5, "F");
        doc.setTextColor(255,255,255); doc.setFontSize(7); doc.setFont("helvetica","bold");
        doc.text(stLabel, ml+148, y+4);

        y += 14;
      });

      addLine(5);

      // ── Recommendations ──────────────────────────────────────────────
      if(result.recommendations?.length){
        checkPage(22);
        doc.setFontSize(9.5); doc.setFont("helvetica","bold"); doc.setTextColor(20,20,20);
        doc.text("RECOMMENDATIONS", ml, y); addLine(1);
        doc.setDrawColor(16,185,129); doc.line(ml, y, ml+48, y); addLine(6);
        result.recommendations.forEach(r=>{
          checkPage(10);
          doc.setFontSize(9); doc.setFont("helvetica","normal"); doc.setTextColor(55,55,55);
          const rLines = doc.splitTextToSize(`-  ${clean(r)}`, mr-ml-5);
          doc.text(rLines, ml+2, y);
          y += rLines.length*5+3;
        });
        addLine(4);
      }

      // ── Disclaimer box ────────────────────────────────────────────────
      checkPage(18);
      doc.setFillColor(248,248,248);
      doc.setDrawColor(200,200,200);
      const discText = "DISCLAIMER: This is an AI-generated analysis for informational purposes only. It is NOT a medical diagnosis. Please consult a qualified doctor for proper medical advice and treatment.";
      const discLines = doc.splitTextToSize(discText, mr-ml-8);
      const discH = discLines.length*4.5+8;
      doc.roundedRect(ml, y, mr-ml, discH, 2, 2, "FD");
      doc.setFontSize(7.5); doc.setFont("helvetica","italic"); doc.setTextColor(120,120,120);
      doc.text(discLines, ml+4, y+6);
      y += discH+4;

      // ── Footer on every page ──────────────────────────────────────────
      const pages = doc.getNumberOfPages();
      for(let i=1;i<=pages;i++){
        doc.setPage(i);
        doc.setFillColor(245,247,250);
        doc.rect(0,285,pw,12,"F");
        doc.setFontSize(7.5); doc.setFont("helvetica","normal"); doc.setTextColor(140,140,140);
        doc.text(`Dr.AI Medical Report Analyzer`, ml, 291);
        doc.text(`Page ${i} of ${pages}`, mr-10, 291, {align:"right"});
      }

      const fname = `Medical_Report_${memberName.replace(/\s+/g,"_")}_${new Date().toISOString().slice(0,10)}.pdf`;
      doc.save(fname);
    } catch(e) {
      console.error("PDF error:", e);
      alert("Could not generate PDF. Please try again.");
    } finally { setDownloading(false); }
  };

  const abnormal   = result?.tests?.filter(t => t.status==="high"||t.status==="low") || [];
  const borderline = result?.tests?.filter(t => t.status==="borderline") || [];
  const p          = result?.patient || {};

  return (
    <div className="mra-overlay" onClick={e => e.target===e.currentTarget && onClose()}>
      <div className="mra-modal">

        {/* Header */}
        <div className="mra-header">
          <div className="mra-header-left">
            <div className="mra-logo">🔬</div>
            <div>
              <h2>Medical Report Analyzer</h2>
              <p>AI-powered lab report explanation in plain English</p>
            </div>
          </div>
          <div className="mra-header-right">
            {result && <>
              <button className="mra-btn-download" onClick={downloadPDF} disabled={downloading}>
                {downloading ? "⏳ Generating..." : "⬇️ Download PDF"}
              </button>
              <button className="mra-btn-new" onClick={reset}>+ New Analysis</button>
            </>}
            <button className="mra-close" onClick={onClose}>✕</button>
          </div>
        </div>

        <div className="mra-body" ref={resultRef}>

          {/* Upload Section */}
          {!result && (
            <div className="mra-upload-section">
              <div className="mra-member-tag">
                <span>{activeMember?.avatar || "👤"}</span>
                <span>Analyzing for: <strong>{memberName}</strong></span>
              </div>

              <div
                className={`mra-dropzone ${dragOver?"drag-over":""} ${file?"has-file":""}`}
                onClick={() => !file && fileRef.current.click()}
                onDragOver={e=>{e.preventDefault();setDragOver(true);}}
                onDragLeave={()=>setDragOver(false)}
                onDrop={handleDrop}
              >
                <input ref={fileRef} type="file" hidden accept=".jpg,.jpeg,.png,.pdf"
                  onChange={e=>handleFile(e.target.files[0])} />
                {!file ? (<>
                  <div className="mra-drop-icon">📂</div>
                  <div className="mra-drop-title">Drop your report here</div>
                  <div className="mra-drop-sub">or click to browse</div>
                  <div className="mra-drop-types">Supports: JPG · PNG · PDF · Max 10MB</div>
                </>) : (
                  <div className="mra-file-preview">
                    {preview
                      ? <img src={preview} alt="report" className="mra-preview-img" />
                      : <div className="mra-pdf-icon">📄</div>}
                    <div className="mra-file-info">
                      <div className="mra-file-name">{file.name}</div>
                      <div className="mra-file-size">{(file.size/1024).toFixed(0)} KB</div>
                      <button className="mra-btn-remove" onClick={e=>{e.stopPropagation();reset();}}>✕ Remove</button>
                    </div>
                  </div>
                )}
              </div>

              {error && <div className="mra-error">⚠️ {error}</div>}

              <div className="mra-supports">
                {["🩸 Blood Test","🧪 Liver Function","🫀 Lipid Profile","🍬 Diabetes","🦠 Thyroid","💊 Prescription","🩻 X-Ray Report","📄 Any Lab Report"].map(r=>(
                  <span key={r} className="mra-support-tag">{r}</span>
                ))}
              </div>

              <button className="mra-btn-analyze" onClick={analyzeReport} disabled={!file||loading}>
                {loading
                  ? <><div className="mra-btn-spinner"/> Analyzing Report...</>
                  : <>🔬 Analyze Report</>}
              </button>
            </div>
          )}

          {/* Results */}
          {result && (
            <div className="mra-results">

              {/* Report title + badge */}
              <div className="mra-result-header">
                <div className="mra-result-type">{result.report_type || "Lab Report"}</div>
                <div className="mra-result-meta">
                  <span>👤 {memberName}</span>
                  {result.report_date && <span>📅 {result.report_date}</span>}
                  <span className={`mra-overall-badge mra-badge-${result.overall_status||"normal"}`}>
                    {result.overall_status==="abnormal" ? "⚠️ Needs Attention" :
                     result.overall_status==="borderline" ? "⚡ Borderline" : "✅ Looks Good"}
                  </span>
                </div>
              </div>

              {/* ── Patient Details Card ── */}
              <div className="mra-patient-card">
                <div className="mra-section-title">👤 Patient Details</div>
                <div className="mra-patient-grid">
                  <div className="mra-patient-field">
                    <span className="mpf-label">Patient Name</span>
                    <span className="mpf-value">{val(p.name) !== "Unknown" ? val(p.name) : memberName}</span>
                  </div>
                  <div className="mra-patient-field">
                    <span className="mpf-label">Age</span>
                    <span className="mpf-value">{val(p.age)}</span>
                  </div>
                  <div className="mra-patient-field">
                    <span className="mpf-label">Gender</span>
                    <span className="mpf-value">{val(p.gender)}</span>
                  </div>
                  <div className="mra-patient-field">
                    <span className="mpf-label">Patient ID</span>
                    <span className="mpf-value">{val(p.patient_id)}</span>
                  </div>
                  <div className="mra-patient-field">
                    <span className="mpf-label">Referred By</span>
                    <span className="mpf-value">{val(p.referred_by)}</span>
                  </div>
                  <div className="mra-patient-field">
                    <span className="mpf-label">Lab / Hospital</span>
                    <span className="mpf-value">{val(p.lab_name)}</span>
                  </div>
                </div>
              </div>

              {/* Summary */}
              <div className="mra-summary">
                <div className="mra-section-title">📋 Summary</div>
                <p>{result.summary}</p>
              </div>

              {/* Alert boxes */}
              {abnormal.length > 0 && (
                <div className="mra-alert mra-alert-red">
                  <div className="mra-alert-title">🔴 Values Needing Attention ({abnormal.length})</div>
                  <div className="mra-alert-items">
                    {abnormal.map((t,i)=>(
                      <span key={i} className="mra-alert-item">{t.name}: {t.value} {t.unit}</span>
                    ))}
                  </div>
                </div>
              )}
              {borderline.length > 0 && (
                <div className="mra-alert mra-alert-yellow">
                  <div className="mra-alert-title">⚠️ Borderline Values ({borderline.length})</div>
                  <div className="mra-alert-items">
                    {borderline.map((t,i)=>(
                      <span key={i} className="mra-alert-item">{t.name}: {t.value} {t.unit}</span>
                    ))}
                  </div>
                </div>
              )}

              {/* Test Table */}
              {result.tests?.length > 0 && (
                <div className="mra-tests">
                  <div className="mra-section-title">🧪 Test Results</div>
                  <div className="mra-table">
                    <div className="mra-table-head">
                      <span>Test Name</span><span>Value</span>
                      <span>Normal Range</span><span>Status</span>
                    </div>
                    {result.tests.map((t,i)=>{
                      const cfg = STATUS_CONFIG[t.status]||STATUS_CONFIG.info;
                      return (
                        <div key={i} className={`mra-table-row mra-row-${cfg.color}`}>
                          <div className="mra-test-name">
                            <span>{t.name}</span>
                            {t.explanation && <span className="mra-test-exp">{t.explanation}</span>}
                          </div>
                          <span className="mra-test-value">{t.value} <span className="mra-unit">{t.unit}</span></span>
                          <span className="mra-test-range">{t.normal_range||"—"}</span>
                          <span className={`mra-status-badge mra-status-${cfg.color}`}>{cfg.icon} {cfg.label}</span>
                        </div>
                      );
                    })}
                  </div>
                </div>
              )}

              {/* Recommendations */}
              {result.recommendations?.length > 0 && (
                <div className="mra-recommendations">
                  <div className="mra-section-title">💡 Recommendations</div>
                  <ul>{result.recommendations.map((r,i)=><li key={i}>{r}</li>)}</ul>
                </div>
              )}

              <div className="mra-disclaimer">
                ⚕️ This is an AI-generated analysis for informational purposes only. It is not a medical diagnosis. Please consult a qualified doctor for proper medical advice.
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
